<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $checklist = [
        'Preparation' => [
            'Parking Brake ON',
            'EFB: Import Flight Plan',
            'EFB: Send Flight Plan to FMC (optional)',
            'EFB: Set Payload and Fuel',
            'Overhead: Battery ON - Close Guard',
            'Overhead: External Power ON',
            'Overhead: Window Heat ON',
            'Overhead: Fire Test Engines / APU',
            'Overhead: Emergency Lights ARMED',
            'Overhead: Emergency Power ARMED',
            'Overhead: Navigation Lights ON',
            'Overhead: Logo Lights ON (if needed)',
            'Overhead: Nav IRS 1 ON',
            'Overhead: Nav IRS 2 ON',
            'Overhead: Nav IRS AUX ON',
            'Hold Standby Artificial Horizon',
            'Set QNH on Standby Altimeter',
            'FMC: Flight Plan Init -> Initialise IRS',
            'FMC: Flight Plan Init -> Enter Origin and Destination',
            'FMC: Flight Plan Init -> Enter Alternate',
            'FMC: Add Flight #',
            'FMC: Add Cruise Altitude',
            'FMC: Add Cost Index',
            'FMC: Add Temp / Wind',
            'FMC: Init Page 2: Drop in Weights',
            'FMC: F-PLN: Add SID and STAR',
            'FMC: Performance -> Climb Data',
            'FMC: Enter Wind Information from OFP for FL100, FL250, FL350',
            'FMC: Format Wind : Example: 10000/233/008 HEIGHT/DEGREES/SPEED',
            'EFB: Takeoff Performance Calculator',
            'FMC: TO/APPR: Enter Flex / Flap / V1 - VR - V2 / OAT (21C) Example',
            'FMC: TO/APPR: Enter Slope / Wind (EFB: 6kt Headwind with 0.2 Slope) would be 0.2/6',
            'FMC: TO/APPR: Thrust Limits: Select T/O and CLB Profiles (if needed)',
            'EFIS: Set QNH',
            'EFIS: Switch to PLAN and Check Route',
            'MCP: Set Cleared Altitude',
            'MCP: Set Runway Heading and PULL',
            'MCP: Set Speed to 250 knots',
            'Overhead: Anti Ice L/R ON (if needed)',
            'Overhead: Fuel Used Reset',
            'Pedestal: Set Autobrake to TO',
            'Overhead: APU Power ON',
            'Screen: Check Engine Page for APU Start',
            'Overhead: External Power OFF',
            'Overhead: No Smoking ON',
            'Overhead: Seat Belts AUTO',
            'Overhead: APU Bleed ON',
            'Overhead: AUX Pump 1 ON (nosewheel steering)',
            'Overhead: Engine Ignition A/B ON',
            'Lights: Beacon ON',
            'EFB: Remove Ground Power',
            'EFB: Remove Chocks',
            'Radio: SQUAK 2000',
            'Radio: Alt Reporting ON',
            'Autobrake: AUX HYD Pump 1 ON',
            'Overhead: Check Lights',
            'Parking Brake: OFF',
            'Pushback',
            'Set Park Brake when Pushback is COMPLETE',
            'Pedestal: Pull Start Selector 3 (Right Engine)',
            'Pedestal: N2 15% -> Fuel RUN / ON',
            'Overhead: Select Engine Anti Ice ON (if needed)',
            'Pedestal: Wait for Start Selector 3 Light to GO OUT',
            'Pedestal: Pull Start Selector 1 (Left Engine)',
            'Pedestal: N2 15% -> Fuel RUN / ON',
            'Overhead: Select Engine Anti Ice ON (if needed)',
            'Pedestal: Wait for Start Selector 1 Light to GO OUT',
            'Pedestal: Pull Start Selector 2 (Tail Engine)',
            'Pedestal: N2 15% -> Fuel RUN / ON',
            'Overhead: Select Engine Anti Ice ON (if needed)',
            'Pedestal: Wait for Start Selector 2 Light to GO OUT',
            'Overhead: Engine Ice As Required',
            'Overhead: APU Bleed OFF',
            'Overhead: APU Power OFF',
            'Pedestal: Scroll Wheel to Set Flaps',
            'Pedestal: Move Flap Leaver to Dial a Flap Section',
            'Yoke: Set STAB TRIM to FMC value (TO/APPR Page)',
        ],
        'Start Taxi' => [
            'Overhead: Taxi Lights ON',
            'Parking Brake OFF',
            'MCP: Prof Armed',
            'MCP: Nav Armed',
            'Taxi Out',
            'Pedestal: Spoliers Armed',
            'MCP: Check Altitude, Heading, Speed',
        ],
        'Light Configuration' => [
            'Overhead: Navigation Lights ON',
            'Overhead: Logo Lights ON (if needed)',
            'Overhead: Runway Turnoff Lights ON',
            'Overhead: Check Light Configuration',
        ],
        'Before Take Off' => [
            'Parking Brake ON',
            'Overhead: Landing Lights ON x 3',
            'Overhead: Strobe Lights (HIGH INT) ON',
            'Radio: TA/RA ON',
            'MCP: Autoflight Click (Takeoff ARMED)',
            'Parking Brake OFF',
            'Pedestal: Throttle 70%',
        ],
        'Climb' => [
            'Gear UP',
            'Pedestal: AT FR on tape: Flaps to SLAT position',
            'Pedestal: AT SR on tape: Flaps to FULLY UP position',
            'MCP: Set Altitude',
            'MCP: Check still in PROF mode',
            'MCP: Autopilot ON',
            'EFIS: Move to STANDARD Pressure (pull)',
        ],
        'After Take Off' => [
            'Pedestal: Disarm Spoilers',
            'Autobrake OFF',
            'Overhead: Turnoff Lights OFF',
            'Overhead: Seat Belts OFF',
            'Overhead: 10k Landing Lights OFF',
            'Pedestal: Set Dial a Flap to 15',
        ],
        'Cruise' => [
            'MCP: Pull Altitude Knob to Climb Now (optional)',
            'MCP: Pull Heading Knob to follow HDG Mode (optional)',
            'EFB: Landing Performance',
        ],
        'Descent' => [
            'Set QNH on Standby Altimeter',
            'EFIS: Set QNH',
            'FMC: TO/APPR: Check 35/Land',
            'EFIS: Set Baro to MINIMUMS',
            'Autobrake SET',
            'Overhead: 10k: Landing Lights ON',
            'Overhead: Seat Belts ON',
            'Pedestal: Flaps FIRST position (SLATS OUT)',
            'Pedestal: Speedbrakes (if needed)',
        ],
        'Landing' => [
            'MCP: Press APPR/LAND when established on ILS',
            'Pedestal: Speedbrakes ARMED',
            'Gear DOWN',
            'Pedestal: Flaps 35',
            'MCP: AUTOPILOT OFF at 1000 ft',
        ],
        'Post Flight' => [
            'Pedestal: Flaps UP',
            'Pedestal: Speedbrake UP',
            'Overhead: Landing Lights OFF',
        ],
        'Power Down' => [
            'Overhead: Taxi lights OFF',
            'EFB: Chocks SET',
            'EFB: Ground Power ON',
            'Overhead: Seatbelts OFF',
            'Overhead: Ground Power ON',
            'Pedestal: Engines Off (3, 1, 2)',
            'Clean up',
        ],
    ];

    return view('checklist', [
        'checklist' => $checklist,
    ]);
});
